In [1]:
import tensorflow as tf
import numpy as np

d:\python\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
x=tf.constant([[1,2,3],[1,2,3],[1,2,3]])
print('x',x.shape)
y=tf.constant([[2,1,1],[2,1,1],[2,1,1]])###这两个是tensor
print('y',y.shape)
x1=([[1,2,3],[1,2,3],[1,2,3]])
y1=([[2,1,1],[2,1,1],[2,1,1]])

x (3, 3)
y (3, 3)


In [3]:
x

<tf.Tensor 'Const:0' shape=(3, 3) dtype=int32>

In [4]:
y

<tf.Tensor 'Const_1:0' shape=(3, 3) dtype=int32>

In [5]:
x1

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [6]:
y1

[[2, 1, 1], [2, 1, 1], [2, 1, 1]]

In [3]:
z=tf.multiply(x,y)   ## element_wise
z1=tf.matmul(x,y)    # 矩阵乘法
print('z',z.shape)
print('z1',z1.shape)
z2 = np.dot(x1,y1)     # 矩阵乘法
print('dot\n',z2)
z3 = np.multiply(x1,y1)   ## element_wise
print('np.multiply\n',z3)

z (3, 3)
z1 (3, 3)
dot
 [[12  6  6]
 [12  6  6]
 [12  6  6]]
np.multiply
 [[2 2 3]
 [2 2 3]
 [2 2 3]]


In [12]:
with tf.Session() as sess:
    print('tf.multiply\n',sess.run(z))
    print('tf.matmul\n',sess.run(z1))
    print(sess.run(np.dot(x,y)))###使用sess.run(np.dot(x,y))输出结果为点乘结果，直接计算np.dot(x1,y1)结果为矩阵乘法.

tf.multiply
 [[2 2 3]
 [2 2 3]
 [2 2 3]]
tf.matmul
 [[12  6  6]
 [12  6  6]
 [12  6  6]]
[[2 2 3]
 [2 2 3]
 [2 2 3]]
