In [1]:
import tensorflow as tf

d:\python\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
A = [1.0,2.0,3.0,4.0,5.0,6.0]

In [3]:
with tf.Session() as sess: 
    print(sess.run(tf.nn.softmax(A)))

[0.00426978 0.01160646 0.03154963 0.08576079 0.233122   0.6336913 ]


In [6]:
import numpy as np

In [24]:
B = np.array( [[1.0,2.0,3.0,10.0],
    [4.0,5.0,6.0,11.2]])

In [25]:
B.shape

(2, 4)

In [26]:
type(B)

numpy.ndarray

In [27]:
with tf.Session() as sess: 
    print(sess.run(tf.nn.softmax(B,0)))

[[0.04742587 0.04742587 0.04742587 0.23147522]
 [0.95257413 0.95257413 0.95257413 0.76852478]]


In [28]:
with tf.Session() as sess: 
    print(sess.run(tf.nn.softmax(B,1)))

[[1.23240871e-04 3.35003420e-04 9.10633710e-04 9.98631122e-01]
 [7.40445603e-04 2.01273983e-03 5.47119410e-03 9.91775620e-01]]


In [30]:
c = [0.00426978,0.01160646,0.03154963,0.08576079,0.233122,0.6336913 ]

In [31]:
type(c)

list

In [33]:
c[0]+c[1]+c[2]+c[3]+c[4]+c[5]

0.99999996

In [34]:
d = [1.23240871e-04, 3.35003420e-04, 9.10633710e-04, 9.98631122e-01]

In [35]:
d[0]+d[1]+d[2]+d[3]

1.000000000001