In [2]:
import numpy as np
import tensorflow as tf

d:\python\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])   # 2行3列

In [5]:
sess = tf.Session()
mean_none = sess.run(tf.reduce_mean(x))
mean_0 = sess.run(tf.reduce_mean(x, 0))
mean_1 = sess.run(tf.reduce_mean(x, 1))

In [6]:
print (x)
print (mean_none)   # (1+2+3+4+5+6)/6=3.5---所有元素求平均
print (mean_0)      # （1+4）/2=2.5， （2+5）/2=3.5， （3+6）/2=4.5 对2行就平均
print (mean_1)      # 对3列求平均
sess.close()

[[1. 2. 3.]
 [4. 5. 6.]]
3.5
[2.5 3.5 4.5]
[2. 5.]
